apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-postgres-volume
  labels:
    type: local
    app: orders-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql